/**
 * Language switching for the analyst UI.
 *
 * Translates by walking text nodes rather than by templating every string.
 * The dashboard mixes text and markup heavily and re-renders whole sections on
 * each refresh; threading a t() call through all of that would have meant
 * touching nearly every line for a feature that is, in the end, a lookup.
 *
 * Only exact matches of known phrases are replaced, so incident data — domain
 * names, hosts, model output — passes through untouched. Nothing generated by
 * a model is ever translated: an analyst reads what the model actually said.
 *
 * Default is Spanish. The jury is in Panamá.
 */
(function () {
  const DICT = {
    // ── Navigation and chrome ────────────────────────────────────────────
    "Skip to dashboard": "Ir al panel",
    "Primary navigation": "Navegación principal",
    "WORKSPACE": "ESPACIO",
    "Workspace": "Espacio",
    "TOOLS": "HERRAMIENTAS",
    "Local workspace": "Espacio local",
    "Security operations": "Operaciones de seguridad",
    "Overview": "Resumen",
    "Incidents": "Incidentes",
    "Network health": "Salud de la red",
    "Local intelligence": "Inteligencia local",
    "Open Grafana": "Abrir Grafana",
    "Export incident report": "Exportar informe",
    "Refresh": "Actualizar",
    "On-premise": "En sitio",
    "COMMAND CENTER": "CENTRO DE MANDO",
    "RACS Intelligence overview": "Resumen de RACS Intelligence",
    "Built by RACS Intelligence": "Construido por RACS Intelligence",
    "Sovereign security platform": "Plataforma de seguridad soberana",
    "Your data. Your perimeter.": "Tus datos. Tu perímetro.",
    "Local detection.": "Detección local.",
    "On-device intelligence.": "Inteligencia en el dispositivo.",
    "LOCAL ENVIRONMENT": "ENTORNO LOCAL",

    // ── Overview ─────────────────────────────────────────────────────────
    "Security overview": "Panorama de seguridad",
    "A clear view of your threats. Complete control of your data.":
      "Una vista clara de tus amenazas. Control completo de tus datos.",
    "Local data connected": "Datos locales conectados",
    "Connecting to local data": "Conectando con los datos locales",
    "Connected intelligence": "Inteligencia conectada",
    "Connecting": "Conectando",
    "Not connected": "Sin conexión",
    "Updated": "Actualizado",
    "SYNTHETIC TELEMETRY": "TELEMETRÍA SINTÉTICA",
    "Local synthetic telemetry": "Telemetría sintética local",
    "Detected incidents": "Incidentes detectados",
    "High-risk incidents": "Incidentes de riesgo alto",
    "Network experience": "Experiencia de red",
    "Monitored sites": "Sedes monitoreadas",
    "Deterministic risk score ≥ 70": "Puntaje determinista ≥ 70",
    "Average across 2 reporting sites": "Promedio de las sedes que reportan",
    "Sites reporting DNS experience": "Sedes que reportan experiencia DNS",
    "with visual evidence": "con evidencia visual",
    "Threat landscape": "Panorama de amenazas",
    "Incident risk across your observed domains": "Riesgo por dominio observado",
    "Risk scores for the highest-risk observed incidents":
      "Puntajes de los incidentes de mayor riesgo",
    "RISK SCORE": "PUNTAJE",
    "Deterministic · 0–100": "Determinista · 0–100",
    "High risk ≥ 70": "Riesgo alto ≥ 70",
    "Observed risk": "Riesgo observado",
    "Detection breakdown": "Desglose de detecciones",
    "Evidence, classified at the source": "Evidencia, clasificada en el origen",
    "Risk is scored by detection engines. AI explains the evidence.":
      "El puntaje lo calculan los motores de detección. La IA explica la evidencia.",
    "incidents": "incidentes",

    // ── Incidents ────────────────────────────────────────────────────────
    "Incident feed": "Flujo de incidentes",
    "Incident investigation": "Investigación de incidentes",
    "INCIDENT INVESTIGATION": "INVESTIGACIÓN DE INCIDENTES",
    "Prioritize the signal. Inspect the evidence.":
      "Prioriza la señal. Inspecciona la evidencia.",
    "Follow the evidence from DNS signals to local visual analysis.":
      "Sigue la evidencia desde las señales DNS hasta el análisis visual local.",
    "Search incidents": "Buscar incidentes",
    "Search domain, site, host…": "Buscar dominio, sede, host…",
    "Filter by risk": "Filtrar por riesgo",
    "All risk levels": "Todos los niveles",
    "High risk · 70+": "Riesgo alto · 70+",
    "Medium · 40–69": "Medio · 40–69",
    "Low · below 40": "Bajo · menos de 40",
    "Detection / domain": "Detección / dominio",
    "Risk": "Riesgo",
    "Site": "Sede",
    "Confidence": "Confianza",
    "Details": "Detalle",
    "Evidence": "Evidencia",
    "DNS evidence": "Evidencia DNS",
    "Close incident details": "Cerrar el detalle",
    "Open full screenshot": "Abrir la captura completa",
    "Suspicious page captured in the isolated local browser":
      "Página sospechosa capturada en el navegador aislado local",
    "No incidents match these filters.": "Ningún incidente coincide con estos filtros.",
    "No incidents yet. Waiting for detections from the local stream.":
      "Aún no hay incidentes. Esperando detecciones del flujo local.",
    "Awaiting incident data": "Esperando datos de incidentes",
    "Waiting for incident data": "Esperando datos de incidentes",
    "Connecting to the incident feed…": "Conectando con el flujo de incidentes…",
    "No domain recorded": "Sin dominio registrado",
    "No action recorded.": "Sin acción registrada.",
    "No visual description recorded.": "Sin descripción visual registrada.",
    "Insufficient evidence": "Evidencia insuficiente",
    "Incident report exported locally.": "Informe exportado localmente.",
    "Connect to the local data source before exporting.":
      "Conéctate a la fuente de datos local antes de exportar.",

    // ── Network health ───────────────────────────────────────────────────
    "DNS experience by site": "Experiencia DNS por sede",
    "Understand DNS experience and its connection to security events.":
      "Entiende la experiencia DNS y su relación con los eventos de seguridad.",
    "QoE score": "Puntaje QoE",
    "p95 latency": "latencia p95",
    "No latency measured": "Sin latencia medida",
    "SOC + NOC": "SOC + NOC",
    "Security signals meet network operations":
      "Las señales de seguridad se cruzan con las operaciones de red",
    "Operational": "Operacional",
    "Security driven": "Impulsado por seguridad",
    "Mixed signals": "Señales mixtas",
    "Unknown": "Desconocido",
    "Awaiting site health": "Esperando salud de las sedes",
    "Waiting for site telemetry": "Esperando telemetría de sedes",
    "No site telemetry yet": "Aún no hay telemetría de sedes",
    "No site telemetry recorded yet.": "Aún no se ha registrado telemetría de sedes.",
    "Waiting for correlation data": "Esperando datos de correlación",
    "No reasoning recorded.": "Sin razonamiento registrado.",

    // ── Local runtime ────────────────────────────────────────────────────
    "Intelligence stays here": "La inteligencia se queda aquí",
    "See what runs on your machine, and why the investigator acts.":
      "Mira qué corre en tu máquina, y por qué el investigador actúa.",
    "Model availability and measured runtime activity":
      "Disponibilidad de modelos y actividad medida",
    "Stream": "Flujo",
    "Events consumed": "Eventos consumidos",
    "Text analyst": "Analista de texto",
    "Vision analyst": "Analista visual",
    "Execution": "Ejecución",
    "Execution device": "Dispositivo de ejecución",
    "On-device": "En el dispositivo",
    "Zero-egress counters": "Contadores de zero-egress",
    "Egress counters": "Contadores de salida",
    "Investigation decisions": "Decisiones de investigación",
    "No decisions available.": "Sin decisiones registradas.",
    "Agent not running": "El agente no está corriendo",
    "The agent is currently offline.": "El agente está apagado.",
    "The agent must be running to report counters.":
      "El agente debe estar corriendo para reportar contadores.",
    "Runtime details appear during a run.":
      "Los detalles aparecen durante una corrida.",
    "Availability is measured during a run.":
      "La disponibilidad se mide durante una corrida.",
    "Text model availability must be confirmed by a running agent.":
      "La disponibilidad del modelo la confirma un agente en ejecución.",
    "Connecting to the local agent…": "Conectando con el agente local…",
    "QVAC is reviewing the evidence on this machine.":
      "QVAC está revisando la evidencia en esta máquina.",
    "Local inference · may take a few moments":
      "Inferencia local · puede tardar unos momentos",
    "Local analysis failed:": "El análisis local falló:",
    "Connection interrupted": "Conexión interrumpida",
    "Unexpected response format": "Formato de respuesta inesperado",
    "Updates every 4 seconds": "Se actualiza cada 4 segundos",
    "Waiting for the first refresh": "Esperando la primera actualización",
    "Waiting for telemetry": "Esperando telemetría",
    "Waiting for data": "Esperando datos",
    "Not measured": "Sin medir",
    "Local-first DNS security": "Seguridad DNS local por diseño",
  };

  const STORE = "racs.lang";
  let lang = localStorage.getItem(STORE) || "es";

  const translate = (text) => (lang === "es" && DICT[text]) || text;

  /** Remembers each node's original English so switching back is lossless. */
  function apply(root = document.body) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    for (let n = walker.nextNode(); n; n = walker.nextNode()) nodes.push(n);

    for (const node of nodes) {
      const raw = node.__i18nSource ?? node.nodeValue;
      const key = raw.trim();
      if (!key) continue;
      const hit = DICT[key];
      if (!hit && !node.__i18nSource) continue;
      node.__i18nSource = raw;
      node.nodeValue = raw.replace(key, lang === "es" ? (hit ?? key) : key);
    }

    for (const el of root.querySelectorAll("[aria-label],[placeholder],[title]")) {
      for (const attr of ["aria-label", "placeholder", "title"]) {
        const raw = el.getAttribute(attr);
        if (!raw) continue;
        const src = el.dataset[`i18n${attr}`] ?? raw;
        if (!DICT[src.trim()] && !el.dataset[`i18n${attr}`]) continue;
        el.dataset[`i18n${attr}`] = src;
        el.setAttribute(attr, lang === "es" ? translate(src.trim()) : src);
      }
    }
    document.documentElement.lang = lang;
  }

  function mountSwitcher() {
    // Into the topbar's action area, beside the environment pill — prepending
    // to .topbar itself would drop it in front of the breadcrumb.
    const host = document.querySelector(".topbar-actions") ||
                 document.querySelector(".topbar") || document.body;
    const box = document.createElement("div");
    box.className = "lang-switch";
    box.innerHTML =
      `<button type="button" data-lang="es" aria-label="Español">ES</button>` +
      `<button type="button" data-lang="en" aria-label="English">EN</button>`;
    box.addEventListener("click", (e) => {
      const btn = e.target.closest("[data-lang]");
      if (!btn) return;
      lang = btn.dataset.lang;
      localStorage.setItem(STORE, lang);
      mark();
      apply();
    });
    host.prepend(box);
    mark();
  }

  const mark = () => document.querySelectorAll(".lang-switch [data-lang]")
    .forEach((b) => b.classList.toggle("is-on", b.dataset.lang === lang));

  window.RacsI18n = { apply, get lang() { return lang; } };

  document.addEventListener("DOMContentLoaded", () => {
    mountSwitcher();
    apply();
    // The dashboard replaces whole sections on refresh, so re-apply after each.
    new MutationObserver((muts) => {
      for (const m of muts) {
        for (const n of m.addedNodes) {
          if (n.nodeType === 1) apply(n);
        }
      }
    }).observe(document.body, { childList: true, subtree: true });
  });
})();
